### PR TITLE
Display validation errors on submit (issue #100)

### PR DESCRIPTION
**Pull request by josefguenther**
This resolves issue #100.

I ran into two further issues that are also bundled into this PR:
- Canary fails in a lot of places... I disabled the test... I don't believe it's a good idea to test against canary, but if you disagree, tell me.
- Beta tests were failing because of the dummy templates, so I fixed those.

Both of those issues are totally unrelated to this PR but I bundled them in so the tests would pass. This might also help other PRs that are open and failing.

### CODE REVIEW

**Comment by GCorbel** [comment]
It's good for me. I just wait for the validation of @spruce .

There is some part I resolved with https://github.com/piceaTech/ember-rapid-forms/pull/104 but nothing important.

**Comment by spruce** [comment]
Hi,
actually I like to have the canary tests in. Which are allowed to fail. Just as a heads-up for the next versions so we can see if sth is changing there.
Maybe you could also add test cases for the versions between 2.1 and current release? I meant to do it yesterday but didn't ...

Otherwise 👍

**Comment by josefguenther** [comment]
So.... If I skip the last commit we're good? I know many people won't merge a failing PR. It will fail on canary.


You mean add 2.2 2.3 and 2.4?


Josef


-----


Sent from my android phone.



From: Felix Fichte

Sent: Wednesday, April 20, 14:45

Subject: Re: [piceaTech/ember-rapid-forms] Display validation errors on submit (issue #100) (#108)

To: piceaTech/ember-rapid-forms

Cc: josefguenther, Author



Hi,

actually I like to have the canary tests in. Which are allowed to fail. Just as a heads-up for the next versions so we can see if sth is changing there.

Maybe you could also add test cases for the versions between 2.1 and current release? I meant to do it yesterday but didn't ...


Otherwise 👍

**Comment by spruce** [comment]
But I think it would fail. Because it is allowed to fail on canary because it's marked as such
```
// .tavis.yml
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
```

Yeah. that's what I meant

**Pull request closed without merging**
