### PR TITLE
Upgrading multiple things

### PR DESCRIPTION
**Pull request by spruce**
I did multiple things:
- Upgrade ember and ember-cli to 2.16
- use ember-bootstrap
- use ember-font-awesome (will be possible to strip out all unused icons with efa:4.0.0 and later)
- fix some stuff inside the docs

I hope that every commit speaks for itself.

### CODE REVIEW

**Comment by spruce** [comment]
I will rebase it after #174 got merged

**Comment by GCorbel** [comment]
I merged #174 . TravisCi fail.

**Comment by spruce** [comment]
Yes I know. Maybe gonna work more on that in the next week. Currently other things to do.

**Comment by spruce** [comment]
@GCorbel can you look into why the ember-lts-2-12 build fails? I can't figure it out. It is somehow not installing the correct version of `ember-source`

**Comment by GCorbel** [comment]
It finally works but we use bower in ember-try. I don't know why it don't work with npm.

**Comment by GCorbel** [comment]
@spruce are we ready to merge this PR?

**Comment by spruce** [comment]
Yes. I think so. Only thing gonna have to check later is the npm vs. bower stuff.

**Pull request merged**
