### PR TITLE
Add `required` and `autofocus` attributes to `html-input` component.

### PR DESCRIPTION
**Pull request by oozzal**
The attributes were already present on the component class but not assigned on the template file.

### CODE REVIEW

**Comment by GCorbel** [comment]
Seems to be nice. I will test it and merge it this morning.

**Comment by GCorbel** [comment]
It works. Can you add this properties on the list of properties in the dummy application [here](https://github.com/piceaTech/ember-rapid-forms/blob/master/tests/dummy/app/templates/controls/input.hbs). Thanks!

**Comment by oozzal** [comment]
@GCorbel Done. I added documentation for remaining other attributes as well.

**Comment by GCorbel** [comment]
Thanks!

**Pull request merged**
