### PR TITLE
Cleanup of components

### PR DESCRIPTION
**Pull request by spruce**
Cleanup of the templates. In most cases when there is access to mainComponent most properties can be accessed directly on mainComponent. Which increases couppling but makes maintaining the templates easier.

### CODE REVIEW

**Comment by GCorbel** [comment]
@spruce it's a good idea but you have to rebase (sorry)

**Comment by GCorbel** [comment]
Thanks for changes. Tests are not working but it seems to be a Github issue. I will give it a try later.

**Comment by GCorbel** [comment]
Sorry but some tests are failing. Can check it?

**Comment by spruce** [comment]
It's not really a github issue. The scond build went through but failed nevertheless. See https://travis-ci.org/piceaTech/ember-rapid-forms/jobs/142590804

**Comment by spruce** [comment]
We can close this PR as of #146, right @GCorbel?

**Pull request closed without merging**
