### PR TITLE
[proposal] Refactoring

### PR DESCRIPTION
**Pull request by GCorbel**
This is a work in progress. All tests are passing. I want your opinions before to continue.

The only interesting commit is : https://github.com/piceaTech/ember-rapid-forms/commit/2860f65d75e596e91e44d4e6ec978072d4e62bb3 . I have a rebase to do.

I don't like the fact every components extends FormGroup. It's not clear and I fill I'm lost when I have something to change. My proposal is a kind of inversement of dependencies. I have [this template](https://github.com/piceaTech/ember-rapid-forms/blob/2860f65d75e596e91e44d4e6ec978072d4e62bb3/addon/templates/components/em-input.hbs) which call the input and `em-form-group`. All attributes are passed but I think we can use something like `inputComponent=this` to reduce the number.

I think `em-input` is cleaner but it will be a little bit different for other components. We still need `html-...`, it will be a little bit less clear.

What you think ? Do you like it ?

### CODE REVIEW

**Comment by spruce** [comment]
So you essentially don't inherit from form-group component anymore? and you put inside the template em-input also em-form-group. So far it looks good. Nice way to clean up the messy templates.

**Comment by spruce** [comment]
You still planning to go through with this?

**Comment by GCorbel** [comment]
Yes, I will have more time soon.

2017-02-13 5:41 GMT-05:00 Felix Fichte <notifications@github.com>:

**Comment by GCorbel** [comment]
I continued to work on this PR. As you can see, I inversed dependencies in all components. The main benefit is show here : https://github.com/piceaTech/ember-rapid-forms/pull/146/commits/bffe8fa65b20c00b64b31f8a2019f60c4769f38d . I can remove all `html-*` components. It will be a lot clearer and easier to maintain. 

I have to finish but let me know what you think.

**Comment by spruce** [comment]
Looks promising to me.

**Comment by GCorbel** [comment]
I continued to do a lot of refactoring. I think it's ready to use but let me know what you think. I can fix small issues to have a better score on code climate.

**Comment by GCorbel** [comment]
I still have small things to do. I have to fix test and reduce the long parameter list. I hope to do that this week end.

**Comment by spruce** [comment]
Looks really promising. Thanks for doing so much work. In the meantime I will create another PR fixing the failing tests.

**Comment by GCorbel** [comment]
I continued to work. We have the score of 4 on code climate !!! 

I decided to remove the call to `form-control` and to always call `em-form-control`, I think it makes more sense.

Tests are failing. I tried to fix it but I don't understand. It seems mixins are not working with latest version. Can you give it a try ?

Thanks !

**Comment by spruce** [comment]
I can't push to your branch so I created a new one with one extra commit in it the branch GCorbel-refactoring

**Comment by spruce** [comment]
I now fixed all errors in the branch mentioned.

**Comment by GCorbel** [comment]
I changed everything in my project for the new version and it seems to work.

**Comment by spruce** [comment]
Sorry for not answering. I was on a vacation. Gonna do a last review in the next few days and then merge it if that's ok with you.

**Comment by GCorbel** [comment]
Yes it's correct. You can merge when you want.

**Comment by spruce** [comment]
Thanks for that much work on this PR. It is greatly appreciated.

**Pull request merged**
