### PR TITLE
CID for select, textarea and checkbox controls

### PR DESCRIPTION
**Pull request by asermax**
Related to #42, I tried to fix the `cid` property for the rest of the controls. This seems to be working alright, but I'm not 100% sure about the workaround for the checkbox one (since the component itself is the control, not like in the other components).
Please give it a look and let me know!

### CODE REVIEW

**Comment by spruce** [comment]
LGTM. I would love if you could add some tests for that? Gonna merge it tomorrow anyway.

**Comment by asermax** [comment]
I asume you mean checking if the id for the controls is correctly set by the `cid`, will give it a try :>

**Comment by spruce** [comment]
yes. that's what I meant. Nice catch BTW.

**Comment by asermax** [comment]
Added some, one for each control since it depends on the component. The label check is probably redundant but oh well d: let me know if I should add/fix something :+1:

**Pull request merged**
