### PR TITLE
Fix a bug with rerendering

### PR DESCRIPTION
**Pull request by GCorbel**
Sorry but I introduced a bug with rerendering. When it go [here](https://github.com/piceaTech/ember-rapid-forms/compare/master...GCorbel:master#diff-c238abb7d2035c748484d1ac607b3761L87) it created an infinite loop.

### CODE REVIEW

**Comment by spruce** [comment]
Is there a way totest that?

**Comment by GCorbel** [comment]
I will try to add a test.

**Comment by GCorbel** [comment]
Sorry but I can't reproduce it and I didn't have the time to go deeper right now. It seems to be related to ember-data and a belongsTo but I tried to reproduce it in the dummy app and it works. This PR solve the problem in my real app.

**Comment by spruce** [comment]
Could you share the dummy app? So I could look into it.

**Comment by GCorbel** [comment]
I just tried on the app under `tests/dummy`.

2017-06-11 14:54 GMT-04:00 Felix Fichte <notifications@github.com>:

**Comment by spruce** [comment]
It's getting better every day. I just wait some more 👍

**Comment by GCorbel** [comment]
I had some troubles with that (harder I expected). Now it works. You can wait a little before to merge.

**Pull request merged**
