### PR TITLE
Add Property is Model support for Select

### PR DESCRIPTION
**Pull request by nobesnickr**
Adding some checks to support Select options from Ember data objects and implementing the propertyIsModel flag

### CODE REVIEW

**Comment by spruce** [comment]
Thanks for the contribution. 
Can You add some tests which show that it works the way You intended to?
(You might want to add yourself to the README as Contributer)

**Comment by nobesnickr** [comment]
I'll get the tests pushed up tomorrow, having some trouble getting the addon dev functionality working so these few changes have been made manually in github editor :(

**Comment by nobesnickr** [comment]
Unfortunately I'm not having much luck getting the tests going and my unfamiliarity with Ember is starting to shine through. @spruce Is there any way you can get the em-select-test.js working on the existing functionality and I can expand on it to include the tests for the latest changes?

With the above changes I was able to use em-select with models with the following example:

pods/client/model.js
```javascript
import Ember from 'ember';
import DS from 'ember-data';
export default DS.Model.extend({
    name: DS.attr('string')
});
```

pods/user/model.js
```javascript
import Ember from 'ember';
import DS from 'ember-data';
export default DS.Model.extend({
    username: DS.attr('string'),
    client: DS.belongsTo('client')
});
```

pods/user/template.hbs
```hbs
{{#user-form model=model action="saveEntity"}}{{/user-form}}
```

pods/components/user-form/component.js
```javascript
export default Ember.Component.extend({
    clientOptions: Ember.computed(function(){
        var model = this.get("model");
        return model.store.findAll('client');
  })
});
```

pods/components/user-form/template.hbs
```
{{#em-form formlayout="horizontal" model=model submitButton=true}}
    {{em-select property="client" label="Client" content=clientOptions propertyIsModel=true optionValuePath="id" optionLabelPath="name" prompt="--select--"}}
    {{em-input property="username" label="Username" placeholder="Enter a name..."}}
{{/em-form}}
```

**Comment by spruce** [comment]
I will add these tests back as soon as possible. Than you can look onto how to make yours work.

**Comment by spruce** [comment]
Gonna close this one in favor of #70. Thanks for the great idea.

**Pull request closed without merging**
