### PR TITLE
Replace bindings by aliases

### PR DESCRIPTION
**Pull request by GCorbel**
This solve the issue #102 .

### CODE REVIEW

**Comment by GCorbel** [comment]
@spruce can you take a look at that. I need to merge it fast because I need it.

**Comment by spruce** [comment]
Could add a small test testing if your problem now works?

But nice work otherwise

**Comment by GCorbel** [comment]
I tried to add a integration test but I'm not able to reproduce it.

I did this : 

```
import {
  moduleForComponent,
  test
}
from 'ember-qunit';
import DS from 'ember-data';
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';

/* globals ok:true */

moduleForComponent('em-form', 'component:em-form ember-data', {
  // Specify the other units that are required for this test
  integration: true
});


var somePerson = Ember.Object.create({
  name: 'my-name',
  errors: DS.Errors.create(),
  validate() {
    var promise = new Ember.RSVP.Promise((resolve) => {
      resolve('ok!');
    });
    return promise;
  }
});

test('errors still correctly refreshed', function(assert) {
  assert.expect(2);

  this.set('someModel', somePerson);
  this.on('submit', function() {
    ok(true, 'submit action invoked!');
  });

  Ember.run(() => {
    this.get('someModel.errors').add('name', 'name!');
    this.get('someModel').set('isValid', false);
  });

  this.render(hbs `{{#em-form model=someModel}}{{em-input property="name"}}{{/em-form}}`);

  Ember.run(() => {
    assert.equal(somePerson.get('errors.name.firstObject.message'), 'name!');
    somePerson.set('name', 'something');
    assert.equal(somePerson.get('errors.name.firstObject.message'), null);
  });
});
```

`somePerson.get('errors.name.firstObject.message')` gives always "name!". I think it's because of [those lines](https://github.com/emberjs/data/blob/master/addon%2F-private%2Fsystem%2Fmodel%2Fmodel.js#L359-L370). It have to be a DS.Model instance and I have to pass by the store. I think I have to create an acceptance test and it's a bit overkill for this small test.

What you think?

**Comment by GCorbel** [comment]
I think this is not so important to add test for this PR because I did not introduce a new feature. The overall behavior of the application had not change.

**Pull request merged**
