### PR TITLE
Pr/samsebastian patch 1

### PR DESCRIPTION
**Pull request by spruce**
This PR continues the work on #79.

### CODE REVIEW

**Comment by GCorbel** [comment]
Sorry for very late answer. I did some tiny changes. The only thing before to merge is to add the data used in the doc. You can also replace : 

```
App.ControlsSelectController = Ember.Controller.extend({
    // Ember.A ist only neccessary when prototype-extensions are turned off
    genderOptions: Ember.A([
        {id: 'M', name: 'Male'}
        {id: 'F', name: 'Female'}
        {id: 'O', name: 'Other'}
    ])
})
```

By the real code.

@samsebastian are you agree to do that?

**Comment by GCorbel** [comment]
I didn't saw it was a super old commit. 

@spruce, you can rebase. We also have to be sure it works with : #173 .

**Comment by spruce** [comment]
@GCorbel Will rebase later and try it out with v1.1.0 released

**Comment by spruce** [comment]
@GCorbel I think it is ready to be merged. If you want you also can make a new release. (squash merge starting with "feat: " and the run `npm run release` (you don't seem to have a npm acc ))

**Comment by GCorbel** [comment]
Adding "feat: " seems to be enough. `npm run release` seems to be useless.

**Pull request merged**
