### PR TITLE
Add i18n support

### PR DESCRIPTION
**Pull request by GCorbel**
All is in the title

### CODE REVIEW

**Comment by GCorbel** [comment]
A clean up and unification of all tests will be necessary. There is integration tests in `tests/unit`...

**Comment by spruce** [comment]
Doesn't this change make i18n a hard dependency? What happens if the service doesn't exist?

**Comment by GCorbel** [comment]
i18n is not an hard dependency anymore and it still woks

**Comment by GCorbel** [comment]
I don't know why tests are failing. I will check it.

**Comment by GCorbel** [comment]
It works now.

**Comment by spruce** [comment]
OMG. LGTM 👍

**Pull request merged**
