### PR TITLE
Convert partials to components, and move templates to addon

### PR DESCRIPTION
**Pull request by technomage**
This converts all partials to components, requiring that some data be passed from the previously shared component to the control view and label cmponents used for each control.  In addition Ember 1.11 attribute syntax is now used, and all templates are in the addon directory and incorporated as layout for each component removing any use of the deprecated layoutName.

### CODE REVIEW

**Comment by technomage** [comment]
The travis results show that you were testing for 1.10, which would not be applicable with 1.11.3 the current release version.  If 1.10 support is important I can back out the 1.11 syntax on attributes.  Otherwise the ember-try config needs to be updated for 1.11 and later.  Locally tests pass on Chrome but not PhantomJS.

**Comment by spruce** [comment]
We could use this file verbatim, right?
https://github.com/ef4/liquid-fire/blob/master/config/ember-try.js

**Comment by pedrokiefer** [comment]
LGTM.

I'll update the unit tests as soon as this gets merged.

**Comment by technomage** [comment]
Thanks for the clean up.

**Pull request merged**
