### PR TITLE
Add the model as an argument of the submission

### PR DESCRIPTION
**Pull request by GCorbel**
This can be useful for actions like : 

```
submit(model) {
  model.save();
}
```

### CODE REVIEW

**Comment by danconnell** [comment]
Looks good to me.

You should bump the repo up a version for it, though, as this could be a breaking change for people. I know it would be for my code, since I pass arguments from buttons within the form to identify button submits as being different from the form submit.

**Comment by GCorbel** [comment]
@danconnell can you give a example ? I don't understand why it is a breaking change.

**Comment by danconnell** [comment]
On a couple save actions in my code, I needed to identify where the save was being called from to do something a little different. So I have something like:

```
submit(fromButton) {
  this.get('model').save()
  if (fromButton) {
    ...
  }}
}
```

This works because when the form calls the action, `fromButton` is undefined. With this change, `fromButton` would be the model and would be truthy.

It's easy for me to change my code to accommodate this, so it's not a big deal, but this change would break something like this.

**Comment by spruce** [comment]
@danconnell So you use the same method as the submit "property" for ember forms. And for the method for custom buttons?

**Comment by danconnell** [comment]
@spruce Yes, exactly.

**Comment by spruce** [comment]
@danconnell but it isn't a breaking change as of ember-rapid forms. Moreso a change to the public api. that's why it should be a minor version bump. IMO

**Comment by danconnell** [comment]
Yes, that is what I meant. Thanks

**Pull request merged**
