### PR TITLE
Add focusOut event support for em-input

### PR DESCRIPTION
**Pull request by rabindrat**
Currently em-input doesn't have focusOut event. Added support for `focusOut` event.

### CODE REVIEW

**Comment by GCorbel** [comment]
It looks good. I have to test it a bit later. Thanks for that.

**Comment by rabindrat** [comment]
Thanks @GCorbel

**Comment by spruce** [comment]
LGTM. But I have no time to review it right now, if @GCorbel wants to merge. That's fine with me.

**Comment by GCorbel** [comment]
Hi,

I took a little time to check your PR. Sorry for the delay, I had a Nintendo Switch + Zelda for Christmas. Why not using the `focusOut` event?

I'm sure there is a way to use `focusOut` method in `mixins/input-component.js` but I didn't found a way to do it.

Why you choose to call the event `emFocusOut` instead of `focusOut`?

**Comment by rabindrat** [comment]
Thanks for checking out PR.
I had used `emFocusOut`, due to a minor issue. On bubbling `focusOut` from `em-input->focusOut()`, it was causing a null-pointer exception in `input-component->focusOut`. 
Added a null-check and changed the event to `focusOut`.

**Comment by GCorbel** [comment]
I did some changes : 

```
diff --git a/addon/components/em-input.js b/addon/components/em-input.js
index bc08ac1..7733c4d 100644
--- a/addon/components/em-input.js
+++ b/addon/components/em-input.js
@@ -28,17 +28,6 @@ export default Component.extend(InputComponentMixin, {
     this.set('canShowErrors', false);
   }),
 
-  actions: {
-    /*
-    Listen to the focus out of the form group and display the errors
-    Pass this event as emFocusOut
-     */
-    focusOut() {
-      this.sendAction('emFocusOut');
-      return this.set('canShowErrors', true);
-    },
-  },
-
   /*
   Observes the helpHasErrors of the help control and modify the 'status' property accordingly.
    */
diff --git a/addon/mixins/input-component.js b/addon/mixins/input-component.js
index 7ff9adc..68d684f 100644
--- a/addon/mixins/input-component.js
+++ b/addon/mixins/input-component.js
@@ -119,6 +119,7 @@ export default Mixin.create(HasPropertyMixin, HasPropertyValidationMixin, HasIdM
   Listen to the focus out of the form group and display the errors
    */
   focusOut() {
+    this.sendAction('focusOut');
     return this.set('canShowErrors', true);
   },
 
diff --git a/addon/templates/components/em-input.hbs b/addon/templates/components/em-input.hbs
index 858ea31..d7401e2 100644
--- a/addon/templates/components/em-input.hbs
+++ b/addon/templates/components/em-input.hbs
@@ -15,6 +15,6 @@
     readonly=readonly
     autoresize=autoresize
     maxlength=maxlength
-    focusOut=(action 'focusOut')
+    focusOut=(action focusOut)
   }}
 {{/em-form-group}}
diff --git a/tests/integration/components/em-input-test.js b/tests/integration/components/em-input-test.js
index 631c1f5..e7549d5 100644
--- a/tests/integration/components/em-input-test.js
+++ b/tests/integration/components/em-input-test.js
@@ -69,8 +69,8 @@ test('Input can be autofocused', function(assert) {
 });
 
 
-test('Input can have emFocusOut event', function(assert) {
-  assert.expect(2);
+test('Input can have focusOut event', function(assert) {
+  assert.expect(3);
 
   this.set('fruit', EmberObject.create());
 
@@ -78,9 +78,9 @@ test('Input can have emFocusOut event', function(assert) {
     assert.ok(true);
   });
 
-  this.render(hbs`{{#em-form as |form|}}{{form.input property="asd" model=fruit emFocusOut='focusOutHandler'}}{{/em-form}}`);
+  this.render(hbs`{{#em-form as |form|}}{{form.input property="asd" model=fruit focusOut='focusOutHandler'}}{{/em-form}}`);
 
-  assert.ok(this.$().find('input'), 'input has emFocusOut');
+  assert.ok(this.$().find('input'), 'input has focusOut');
 
   this.$().find('input').click().blur();
 });
```

As you can see, I changed for `focusOut=(action focusOut)` in the template so it use the method in the mixin. I also send the action in the method of the mixin.

I think we should test if it works for other components and we should use it for other actions. There is a [list of actions](https://emberjs.com/api/ember/2.15/classes/Ember.Component#event-names) we should accept but if we add code for all those actions, it will be ugly and tedious. I don't find a better solution at the moment.

What you think ?

**Comment by GCorbel** [comment]
Let me know if I'm wrong but it seems than this pass on the master branch : 

```
test('Input can have focusOut event', function(assert) {
  assert.expect(2);

  this.set('fruit', EmberObject.create());

  this.on('focusOutHandler', function(){
    assert.ok(true);
  });

  this.render(hbs`{{#em-form as |form|}}{{form.input property="asd" model=fruit focusOut=(action 'focusOutHandler')}}{{/em-form}}`);

  assert.ok(this.$().find('input'), 'input has focusOut');

  this.$().find('input').click().blur();
});
```


You can also do : 
```
  this.set('focusOutHandler', function(){
    assert.ok(true);
  });

  this.render(hbs`{{#em-form as |form|}}{{form.input property="asd" model=fruit focusOut=focusOutHandler}}{{/em-form}}`);
```
It is enough for you case?

**Comment by GCorbel** [comment]
Can you try to add your tests on the master branch without modifications on the addon directory to confirm if it works as you wish ?

**Comment by rabindrat** [comment]
Thanks again @GCorbel for your feedback, I've implemented them. 
It would be great to add support to other ember-actions. I could look into adding other actions in similar way but as you mentioned it would add a lot more code, and I don't know of a better way of doing it. 
On other note some of the test fails seems to be other issue like one of the error in Travis was `fatal: unable to access 'https://github.com/piceaTech/ember-rapid-forms.git/':`.

(Not related, but I am getting error in demo app https://puu.sh/yWXZu/76eb0037bc.png
which seems to get fixed by this 
https://github.com/piceaTech/ember-rapid-forms/pull/186/commits/1a544a1b4e3b102b04c0c99da4a24def05f0cde8)

**Comment by GCorbel** [comment]
Thanks for your work but I don't think your code is useful because `focusOut=(action 'focusOut')` already works. I didn't tried but it should work for other actions too. Use `sendAction` send the action two times. A note on the demo can be useful. 

Feel free to reopen the PR if I'm wrong.

**Comment by rabindrat** [comment]
I had been using `focusOut='focusOut'` instead of `focusOut=(action 'focusOut')`. Thanks!

**Comment by GCorbel** [comment]
`focusOut='focusOut'` should work if the action in the `actions` hash of the component or the route, isn't it?

**Comment by rabindrat** [comment]
Sorry for the late reply.
As far as I have tested `focusOut='focusOut'`, as in this ember-twiddle, doesn't seem to work. 
https://ember-twiddle.com/8e00f971848e19ec5f15ab39dea81d0e?openFiles=templates.application.hbs%2C

**Comment by GCorbel** [comment]
You're right. You can also do `focusOut=focusOut` if the `focusOut` action is not in the `actions` hash.

**Pull request closed without merging**
