### PR TITLE
Add classes if the field is required and find if there is a validator.

### PR DESCRIPTION
**Pull request by GCorbel**
This PR depends of the PR #143 . I simply added a class to say if a field is required or not. It is true by default if it find the validator on ember-cp-validations. To add an asterik, we can simply do this css : 

```
.form-group.required .control-label:after { 
   content:"*";
   color:red;
}
```

As you can see on [this SO question](http://stackoverflow.com/questions/23141854/adding-asterisk-to-required-fields-in-bootstrap-3).

### CODE REVIEW

**Comment by spruce** [comment]
Could you add some docs for that feature?

**Comment by spruce** [comment]
Also: The tests fail because of some unknown factory.

**Comment by GCorbel** [comment]
I will add more documentation. I think I will fix the tests once this PR is merged in another PR. This PR is not responsible of the failing test.

**Comment by GCorbel** [comment]
Just to know, what you think about this feature. Do you think it's correct ?

**Comment by spruce** [comment]
Yeah, looks good. Only thing: could bump the version.

**Comment by GCorbel** [comment]
Sorry for the delay. I was off for christmas vacations. I do not have the right to push the new version : 

    you do not have permission to publish "ember-rapid-forms". Are you logged in as the correct user? : ember-rapid-forms

**Comment by spruce** [comment]
What is your username. Couldn't find you on npm

**Pull request merged**
