### PR TITLE
Make it working with Ember 2.8

### PR DESCRIPTION
**Pull request by GCorbel**

### CODE REVIEW

**Comment by GCorbel** [comment]
@spruce It works but tests are failing because of beta version and canary. Do you think I should merge it?

**Comment by spruce** [comment]
So I looked into it. It looks like we are somewhere creating the components directly and not looking them up. At this Commit https://github.com/emberjs/ember.js/commit/22e1612ad07249fddb6a1e0bb2344eba638fab46 rwjblue removed the support for it (File: packages/ember-views/lib/views/core_view.js)

I think the way forward would be to find those places in the test and fix them.


(Some input rwjblue gave someone else in slack yesterday:
```
you need to look components up from the container/registry/owner
Assuming you are using moduleFor in ember-QUnit, you can register Ember.Component and then look it up
That will ensure the renderer (and other injections) are setup
```
)
This will be done like it was done here with the location Service. https://guides.emberjs.com/v2.8.0/testing/testing-components/


(I don't have to much time at hand right now. But I hope this helps you 👍 )

**Comment by GCorbel** [comment]
I works now. @spruce what you think?

**Comment by spruce** [comment]
Looks wonderful 👍

**Comment by flyrev** [comment]
Do you know when a release will be created?

**Comment by GCorbel** [comment]
@flyrev we have to merge this PR #138 and this other one #137 before to do a new release.

**Pull request merged**
