### PR TITLE
Ember 3.0 deprecation fix - issue #189 fix

### PR DESCRIPTION
**Pull request by slannigan**
The problem and solution are outline in this issue: https://github.com/piceaTech/ember-rapid-forms/issues/189

### CODE REVIEW

**Comment by GCorbel** [comment]
It looks good. I have to test. The CI seems to fail because of an issue with `ember-font-awesome`. I will fix this before to validate your PR. I will do this tonight.

**Comment by GCorbel** [comment]
Sorry for the delay, it was longer than I expected (and I had lack of motivation to be honest). I did the PR #191 . I'm waiting for validation by @spruce but I will merge if you approve it.

**Comment by GCorbel** [comment]
I merged my fix. Can you merge master on your branch to see if tests pass?

**Comment by slannigan** [comment]
No problem. Master merged, tests still failing.

**Comment by GCorbel** [comment]
This time it seems to be related to your changes because it pass on the master branch. Can you check it?

**Comment by slannigan** [comment]
Fixed the tests. The reason the tests were failing was because they were expecting the `em-select` to get updated within the same run cycle, which with this PR's fix is no longer the case. I fixed the tests to pass by adding a `ember-test-helpers/wait` call after rendering the `em-select` component, which causes the tests to wait for the `run.next()` to get run before continuing the tests.

**Comment by spruce** [comment]
I just reran the tests out of curiousity and it seems as of now the tests are failing again. Because node 4 is not supported anylonger.

**Comment by GCorbel** [comment]
@slannigan you can merge the master branch and tests should pass now.

**Comment by spruce** [comment]
As of #199 this should also be resolved. Hence I'm closing this.

**Pull request closed without merging**
