### PR TITLE
fix horizontal enlargement

### PR DESCRIPTION
**Pull request by spruce**
Hey,
In my project I always use horizontal mode. But then there was the problem that it always added some pixels to the output even when there was no error to show.
I've got some failing tests. But I don't know why for now. What do You think where should I add the regression tests?

### CODE REVIEW

**Comment by pedrokiefer** [comment]
You have to update `em-form-control-help-test.js` as you changed the binding to the propertyName instead of the whole component. 

If you could write a test for this regression, that would be awesome. From your issue I didn't quite understand what is exactly the problem. I would add the tests to `unit/components/em-form-test.js`, but we could also add something like `unit/regressions/name-of-the-regression.js`.

**Comment by spruce** [comment]
Ahh. I didn't see it. I will come around fixing this tomorrow hopefully.

Well, it isn't strictly a regression. It always was a bug. I think I opt for the first option.

The problem is that when there is no error to show (input is valid) then the helptext is empty but will still be displayed. And that element takes 15 px of hoizontal space. (http://piceatech.github.io/ember-rapid-forms/#/overview click horizontal. enter more then 5 chars, TAB, see all elements below go down 15px)

**Comment by pedrokiefer** [comment]
Now that you explained, I have exactly this issue in one application of mine!

I'll fix the test and merge.

**Comment by spruce** [comment]
You take all the work away so sad for me :cry:

**Comment by pedrokiefer** [comment]
Sorry, I'll try to slow down a bit :)

**Comment by spruce** [comment]
Nice work!!! :+1:

**Pull request merged**
